apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-svc.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "test-svc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: test-svc
    {{- include "test-svc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: test-svc
      {{- include "test-svc.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: test-svc-cm
        - secretRef:
            name: test-svc-secret
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag
          | default .Chart.AppVersion }}
        name: test-svc
        ports:
        - containerPort: 8080
        resources: {}
      nodeSelector:
        kubernetes.io/os: linux
