apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-svc.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "test-svc.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: test-svc
  {{- include "test-svc.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.backend.service.ports.http }}
    targetPort: 8080