apiVersion: v1
kind: Secret
metadata:
  name: test-cli-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "test-cli.labels" . | nindent 4 }}
data:
  DATABASE_USER_PASSWORD: {{ .Values.backend.db.password | b64enc | quote }}
type: Opaque